### ISSUE TITLE
subscriber multithreaded goes to Stopped state right away

### ISSUE THREAD

**Issue by wknd** [elBoberido/iceoryx-rs#3]
The multithreaded example stops right away.

This seems to be because it relies on code that is still on the TODO list.

I created the ticket to signal there is an interest in a rust crate.
I'm currently evaluating if iceoryx is suitable for a work project, and if my employer is going to pay me to re-learn C++ they might as well pay me to learn rust.

Sidenote: as far as I can tell the iceoryx submodule can be updated to v1.0.1 without (additional) breaks.

**Comment by elBoberido** [comment]
Hi @wknd,
sorry that I did not respond that long. I was on vacation and didn't check github.

You are right, this is still work in progress. I hope I can find some time to finish this before iceoryx 2.0 gets released.

The multithreaded example relied on code which was replaced by the so called `WaitSet` and `Listener` with v0.90 and is not yet ported. It should work when polling is used instead of the blocking call.
```rust
loop {
    if sample_receiver.has_samples() {
        while let Some(sample) = sample_receiver.get_sample() {
            println!("Receiving: {}", sample.counter);
        }
    } else {
        thread::sleep(Duration::from_millis(100));
    }
}
```

Are there specific features you are interested in? If possible, I could try to work on them first.

**Comment by elBoberido** [comment]
Hi @wknd

it is now fixed on latest master. I guess I should start thinking about a 0.1 release on crates.io

**Comment by wknd** [comment]
@elBoberido thats great news, I'll try it out this weekend. I really want to use more rust instead of other languages.

I think iceoryx as a whole looks very promising but unfortunately for the work project I think zeroMQ is going to be more suited for our use case (at least with the current version).

From memory what I specifically liked about iceoryx:
- I can do pub/sub and have a premade broker that can handle caching values and late joiners.
- The benchmarks also seemed a lot faster even when I was using much much smaller data size (though I didn't measure if lower latency also translates in lower cpu time)
- The documentation is more up to date than with zeroMQ.

But I'm going the DIY route so I can:
- Use req/rep style to trigger actions and get feedback when its done (maybe coming with 2.0?)
- subscribe to an entire subset of topics, to easily subscribe to partial updates of a larger set, and use it for capability discovery.
  ex:
    '/lights/0/' and '/lights/1/' publish data, by subscribing to 'lights' I now know there are 2 lights.
    '/lights/0/state' publishes, I only have to update the 'state' portion of that light, and know that this type of light has a 'state'

**Comment by elBoberido** [comment]
@wknd I'm not that familiar with zeroMQ but I think it has a slightly different target group than iceoryx and is more comparable to DDS in the sense that the applications can be distributed in the network. Contrary to that, iceoryx is restricted to local communication and either needs a bridge to a networking middleware (like iceoryx_dds) or is itself the base for another framework like eCal or CycloneDDS.

The reason that iceoryx is faster than zeroMQ is most probably that we use a zero copy mechanism via shared memory. This means we are essentially transmitting just a pointer and have therefore a constant latency. I'm not sure if zeroMQ has such an optimization for local communication.

Work is currently quite slow on req/res but the plan is to have it in v2.0. I guess once that is released it will take me a few weeks to create the binding, depending on how much other stuff is going on.

I'm not 100% sure what you mean with the example.  Let me explain it in the iceoryx terminology. We have a so called `ServiceDescription` which has three strings for service, instance and event. In your example, service would be `lights`, instance would be `1` and `2` and event would be `state`. You now want to be able to subscribe to all instances and events of a specific service, right? Furthermore you want to subscribe to a specific event of a specific instance of a specific service, right? The latter is already possible today. The former should be possible once @mossmaurice finishes his work on the service discovery. Maybe not out of the box like having a class to instantiate but more like you get notified when new instances/events of a service emerge in order to manually subscribe to them and then use a `Listener`/`WaitSet` to react on new data. If you want to discuss this further, we could create a github discussion in eclipse-iceoryx so that other devs can also give their input. This might even be a good idea for an example.

**Comment by wknd** [comment]
You're pretty spot on about my example. With the extra catch:
- our data doesn't always nicely fit within a ```ServiceDescription``` without extra workaround.
  but I'm sure I could come up with something that fits within those constraints
- also need to be notified when a  ```ServiceDescription``` is removed (unpublish??)

I know iceoryx it uses zero copy, but my events should be just small state changes with a small amount of data.
So I modified the iceorix benchmark to bench from 64byte to 1kB and it was still consistently 3 times faster than the unix socket method (which is what zeroMQ uses for IPC), which is more than I expected for small data sizes.  

I'm afraid my work project isn't going to be able to wait for 2.0,  
but I'd be happy to give a more detailed description of what I was hopping to accomplish in a github discussion. There might be some overlap with https://github.com/eclipse-iceoryx/iceoryx/discussions/818 and https://github.com/eclipse-iceoryx/iceoryx/discussions/776.

I'll post there this weekend and try to tag you.

**Comment by elBoberido** [comment]
There should be a notification for each state change, so when a publisher stops to offer the service one would be notified.

With small amount of data the time to copy them is insignificant. CPUs are insanely fast at that task. What leads to the higher latency is most probably that there are more context switches with unix sockets since the kernel is involved. With iceoryx everything is in userspace. Well, at least in our benchmark which is polling based. The `Listener`/`WaitSet` can be used to sleep without burning the CPU. With that we also have a context switch due to a semaphore. We want to also include this in the benchmark but did not yet took the time to implement it. The main point of the current benchmark is to show that there are really no copies involved.
